# Generated by Django 2.2 on 2020-04-11 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0004_auto_20200410_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=12, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='题库名称')),
                ('type', models.CharField(choices=[('mc', '单项选择题'), ('mcs', '多项选择题'), ('tf', '判断题')], default='单项选择题', max_length=6, verbose_name='题库类型')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='题目数量')),
                ('intro', models.CharField(max_length=300, verbose_name='简介')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_to', to='role.User', verbose_name='创建者')),
            ],
            options={
                'verbose_name': '题库信息',
                'verbose_name_plural': '题库信息管理',
                'ordering': ('-last_modified_time', '-created_time'),
            },
        ),
    ]
