# Generated by Django 2.2 on 2020-04-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='type',
            field=models.CharField(choices=[('mc', '单项选择题'), ('mcs', '多项选择题'), ('tf', '判断题')], default='mc', max_length=6, verbose_name='题库类型'),
        ),
    ]
