# Generated by Django 2.2 on 2020-04-12 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_singlequestion_singlequestionimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlequestion',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 12, 22, 11, 18, 260383), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlequestion',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
