# Generated by Django 2.2 on 2020-04-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200412_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlequestion',
            name='option_c',
            field=models.CharField(max_length=300, null=True, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='option_d',
            field=models.CharField(max_length=300, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='option_e',
            field=models.CharField(max_length=300, null=True, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='option_f',
            field=models.CharField(max_length=300, null=True, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='topic',
            field=models.TextField(max_length=1000, verbose_name='题干'),
        ),
    ]
