# Generated by Django 2.2 on 2020-04-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200413_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=12, verbose_name='ID')),
                ('topic', models.TextField(max_length=1000, verbose_name='题干')),
                ('answer', models.CharField(max_length=5, verbose_name='答案')),
                ('analysis', models.TextField(verbose_name='试题解析')),
                ('option_a', models.CharField(max_length=300, verbose_name='A')),
                ('option_b', models.CharField(max_length=300, verbose_name='B')),
                ('option_c', models.CharField(max_length=300, null=True, verbose_name='C')),
                ('option_d', models.CharField(max_length=300, null=True, verbose_name='D')),
                ('option_e', models.CharField(max_length=300, null=True, verbose_name='E')),
                ('option_f', models.CharField(max_length=300, null=True, verbose_name='F')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_bank_to', to='exam.QuestionBank', verbose_name='题库')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleQuestionImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('TOPIC', '题干'), ('A', 'A'), ('B', 'B'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=5, verbose_name='对应选项')),
                ('intro', models.CharField(max_length=300, verbose_name='图名')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_question', to='exam.MultipleQuestion', verbose_name='题目')),
            ],
            options={
                'verbose_name': '多项选择试题图片信息',
                'verbose_name_plural': '多项选择试题图片信息管理',
                'ordering': ('-last_modified_time', '-created_time'),
            },
        ),
    ]
