# Generated by Django 2.2 on 2020-04-15 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_multiplequestion_multiplequestionimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeQuestionImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=300, verbose_name='图名')),
                ('img', models.ImageField(upload_to='', verbose_name='图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_question', to='exam.MultipleQuestion', verbose_name='题目')),
            ],
            options={
                'verbose_name': '判断试题图片信息',
                'verbose_name_plural': '判断试题图片信息管理',
                'ordering': ('-last_modified_time', '-created_time'),
            },
        ),
        migrations.CreateModel(
            name='JudgeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=12, verbose_name='ID')),
                ('topic', models.TextField(max_length=1000, verbose_name='题干')),
                ('answer', models.BooleanField(verbose_name='答案')),
                ('analysis', models.TextField(verbose_name='试题解析')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_bank_to', to='exam.QuestionBank', verbose_name='题库')),
            ],
        ),
    ]
