# Generated by Django 2.2 on 2020-04-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_judgequestion_judgequestionimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgequestion',
            name='answer',
            field=models.CharField(choices=[('1', '正确'), ('0', '错误')], max_length=2, verbose_name='答案'),
        ),
    ]
