# Generated by Django 2.2 on 2020-04-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200415_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgequestionimg',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_question', to='exam.JudgeQuestion', verbose_name='题目'),
        ),
    ]
