# Generated by Django 2.2 on 2020-04-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20200415_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgequestion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='multiplequestion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='singlequestion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
