# Generated by Django 2.2 on 2020-04-16 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_auto_20200410_2350'),
        ('exam', '0011_auto_20200415_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=12, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='试卷名称')),
                ('type', models.CharField(choices=[('static', '固定组卷'), ('random', '随机组卷')], max_length=6, verbose_name='组卷类型')),
                ('pass_score', models.PositiveSmallIntegerField(default=60, verbose_name='及格分数')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('editor', '可编辑'), ('publish', '已发布'), ('view', '可查阅')], default='editor', max_length=8, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_creator_to', to='role.User', verbose_name='创建者')),
            ],
            options={
                'verbose_name': '组卷信息',
                'verbose_name_plural': '组卷信息管理',
                'ordering': ('-last_modified_time', '-created_time'),
            },
        ),
        migrations.CreateModel(
            name='ExaminationRandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=12, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='抽题数量')),
                ('score', models.FloatField(default=0.0, verbose_name='每题分数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_random_to', to='exam.QuestionBank', verbose_name='题库')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_random_to', to='exam.Examination', verbose_name='考试')),
            ],
            options={
                'verbose_name': '随机组卷信息',
                'verbose_name_plural': '随机组卷信息',
                'ordering': ('-last_modified_time', '-created_time'),
            },
        ),
    ]
