# Generated by Django 2.2 on 2020-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_examination_examinationrandom'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='total_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='总分'),
        ),
    ]
