# Generated by Django 2.2 on 2020-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_examination_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='考试时间'),
        ),
    ]
