# Generated by Django 2.2 on 2020-04-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_examination_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ('-created_time',), 'verbose_name': '组卷信息', 'verbose_name_plural': '组卷信息管理'},
        ),
        migrations.AlterModelOptions(
            name='examinationrandom',
            options={'ordering': ('created_time',), 'verbose_name': '随机组卷信息', 'verbose_name_plural': '随机组卷信息'},
        ),
        migrations.AlterField(
            model_name='examination',
            name='pass_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='及格分数'),
        ),
    ]
