# Generated by Django 2.2 on 2020-04-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20200419_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='total_score',
        ),
    ]
