# Generated by Django 2.2 on 2020-04-20 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_auto_20200410_2350'),
        ('exam', '0016_remove_examination_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=12, verbose_name='ID')),
                ('has_done', models.BooleanField(default=False, verbose_name='是否已考')),
                ('do_start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始答卷时间')),
                ('do_submit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交卷时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_examiner', to='exam.Examination', verbose_name='考试')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_examiner', to='role.User', verbose_name='考试人员')),
            ],
            options={
                'verbose_name': '考试人员信息',
                'verbose_name_plural': '考试人员信息管理',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.PositiveSmallIntegerField(default=0, verbose_name='题号')),
                ('type', models.CharField(choices=[('mc', '单项选择题'), ('mcs', '多项选择题'), ('tf', '判断题')], default='mc', max_length=6, verbose_name='试题类型')),
                ('answer', models.CharField(max_length=10, null=True, verbose_name='答案')),
                ('score', models.FloatField(default=0.0, verbose_name='每题分数')),
                ('is_true', models.CharField(choices=[('1', '正确'), ('0', '错误')], default='0', max_length=2, verbose_name='是否正确')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_paper', to='exam.Examiner', verbose_name='考试信息')),
                ('judge_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_paper', to='exam.JudgeQuestion')),
                ('multiple_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_paper', to='exam.MultipleQuestion')),
                ('single_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_paper', to='exam.SingleQuestion')),
            ],
            options={
                'verbose_name': '试卷信息',
                'verbose_name_plural': '试卷信息管理',
                'ordering': ('question_num',),
            },
        ),
    ]
