# Generated by Django 2.2 on 2020-04-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_examiner_exampaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlequestionimg',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_question_to', to='exam.SingleQuestion', verbose_name='题目'),
        ),
    ]
