# Generated by Django 2.2 on 2020-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_auto_20200420_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='view',
            field=models.BooleanField(default=False, verbose_name='是否可查阅'),
        ),
    ]
