# Generated by Django 2.2 on 2020-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_examiner_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplequestionimg',
            name='choice',
            field=models.CharField(choices=[('TOPIC', '题干'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=5, verbose_name='对应选项'),
        ),
        migrations.AlterField(
            model_name='singlequestionimg',
            name='choice',
            field=models.CharField(choices=[('TOPIC', '题干'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=5, verbose_name='对应选项'),
        ),
    ]
