# Generated by Django 2.2 on 2020-04-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20200424_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplequestion',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '多项选择试题信息', 'verbose_name_plural': '多项选择试题信息管理'},
        ),
        migrations.AlterModelOptions(
            name='singlequestion',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '单选试题信息', 'verbose_name_plural': '单选试题信息管理'},
        ),
    ]
