# Generated by Django 2.2 on 2020-05-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20200424_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=12, verbose_name='ID')),
                ('question_num', models.PositiveSmallIntegerField(default=0, verbose_name='题号')),
                ('type', models.CharField(choices=[('mc', '单项选择题'), ('mcs', '多项选择题'), ('tf', '判断题')], default='mc', max_length=6, verbose_name='试题类型')),
                ('score', models.FloatField(default=0.0, verbose_name='每题分数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_static_to', to='exam.Examination', verbose_name='考试')),
                ('judge_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_static', to='exam.JudgeQuestion')),
                ('multiple_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_static', to='exam.MultipleQuestion')),
                ('single_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_static', to='exam.SingleQuestion')),
            ],
            options={
                'verbose_name': '固定组卷信息',
                'verbose_name_plural': '固定组卷信息',
                'ordering': ('created_time',),
            },
        ),
    ]
