# Generated by Django 2.2 on 2020-05-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_examinationstatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationstatic',
            name='uuid',
        ),
    ]
