# Generated by Django 2.2 on 2020-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_remove_examinationstatic_question_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
                ('file', models.FileField(upload_to='excel/%Y/%m', verbose_name='文件路径')),
                ('is_static', models.BooleanField(default=False, verbose_name='是否是静态模板')),
                ('type', models.CharField(choices=[('st', '学生'), ('mc', '单项选择题'), ('mcs', '多项选择题'), ('tf', '判断题')], max_length=6, verbose_name='类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'EXCEL模板信息',
                'verbose_name_plural': 'EXCEL模板信息管理',
                'ordering': ('-created_time',),
            },
        ),
    ]
