# Generated by Django 2.2 on 2020-05-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_exceltemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='do_refresh_time',
            field=models.DateTimeField(null=True, verbose_name='最后刷新时间'),
        ),
    ]
