# Generated by Django 2.2 on 2020-05-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_auto_20200509_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='limit_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='请求次数'),
        ),
    ]
