# Generated by Django 2.2 on 2020-05-12 16:16

from django.db import migrations, models
import role.save


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_examiner_limit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='intro',
            field=models.CharField(blank=True, max_length=300, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否生效'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='analysis',
            field=models.TextField(blank=True, verbose_name='试题解析'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='option_e',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='option_f',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否生效'),
        ),
        migrations.AlterField(
            model_name='singlequestionimg',
            name='img',
            field=models.ImageField(storage=role.save.newStorage(), upload_to='question/%Y/%m/', verbose_name='图片'),
        ),
    ]
