# Generated by Django 2.2 on 2020-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_auto_20200512_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judgequestion',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '判断题信息', 'verbose_name_plural': '判断题信息管理'},
        ),
        migrations.AlterModelOptions(
            name='judgequestionimg',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '判断题图片信息', 'verbose_name_plural': '判断题图片信息管理'},
        ),
        migrations.AlterModelOptions(
            name='multiplequestion',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '多项选择题信息', 'verbose_name_plural': '多项选择题信息管理'},
        ),
        migrations.AlterModelOptions(
            name='multiplequestionimg',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '多项选择题图片信息', 'verbose_name_plural': '多项选择题图片信息管理'},
        ),
        migrations.AlterModelOptions(
            name='singlequestion',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '单项选择题信息管理', 'verbose_name_plural': '单项选择题信息管理'},
        ),
        migrations.AlterModelOptions(
            name='singlequestionimg',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '单选题图片信息', 'verbose_name_plural': '单选题图片信息管理'},
        ),
        migrations.AlterField(
            model_name='judgequestion',
            name='analysis',
            field=models.TextField(blank=True, verbose_name='试题解析'),
        ),
        migrations.AlterField(
            model_name='judgequestionimg',
            name='intro',
            field=models.CharField(blank=True, max_length=300, verbose_name='图名'),
        ),
        migrations.AlterField(
            model_name='multiplequestion',
            name='analysis',
            field=models.TextField(blank=True, verbose_name='试题解析'),
        ),
        migrations.AlterField(
            model_name='multiplequestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='multiplequestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='multiplequestion',
            name='option_e',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='multiplequestion',
            name='option_f',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='multiplequestionimg',
            name='intro',
            field=models.CharField(blank=True, max_length=300, verbose_name='图名'),
        ),
    ]
