# Generated by Django 2.2 on 2020-04-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', '教师'), ('student', '学生')], max_length=7, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('nomale', '保密')], default='nomale', max_length=6, verbose_name='性别'),
        ),
    ]
