# Generated by Django 2.2 on 2020-04-10 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20200408_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherstudent',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '师生关系', 'verbose_name_plural': '师生关系管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-last_modified_time', '-created_time'), 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息管理'},
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 10, 11, 24, 50, 792776), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
