# Generated by Django 2.2 on 2020-04-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20200410_1124'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='role_user_usernam_d47c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='role_user_name_fabf38_idx'),
        ),
    ]
