# Generated by Django 2.2 on 2020-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_auto_20200410_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓名'),
        ),
    ]
