# Generated by Django 2.2 on 2020-05-12 16:17

from django.db import migrations, models
import role.save


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_auto_20200511_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.ImageField(default='head/head_img.jfif', storage=role.save.newStorage(), upload_to='head/%Y/%m/', verbose_name='头像'),
        ),
    ]
